config/routes.rb
Ecommerce::Application.routes.draw do
root :controller => 'categoris', :action => 'index'

match '/', :controller => 'pages', :action => 'home'

match 'contact', :controller => 'pages', :action => 'contact'
match 'contact', :controller => 'pages', :action => 'contact'
match 'help', :controller => 'pages', :action => 'help'
match 'about', :controller => 'pages', :action => 'about'
resources :pages 

match 'commandes/:action', :controller => 'commandes', :action => /[a-z]+/i
match 'destroy', :controller => 'commandes', :action => 'destroy'
match 'payement', :controller => 'commandes', :action => 'payement'
match 'mesAchat', :controller => 'commandes', :action => 'mesAchat'
match 'commandeEffectuerUser', :controller => 'commandes', :action => 'commandeEffectuerUser'
resources :commandes 

match 'categoris/:action', :controller => 'categoris', :action => /[a-z]+/i
match 'listProduit', :controller => 'categoris', :action => 'listProduit'
match '/home', :controller => 'categoris', :action => 'index'
resources :categoris

match 'produits/:action', :controller => 'produits', :action => /[a-z]+/i
match 'produits/afficher', :controller => 'produits', :action => 'afficher'
match '/commandeEffectuer', :controller => 'produits', :action => 'commandeEffectuer'
resources :produits

match 'user_sessions/:action', :controller => 'user_sessions', :action => /[a-z]+/i
match 'login', :controller => 'user_sessions', :action => 'new'
match 'logout' => 'user_sessions#destroy', :as => :logout
resources :user_sessions

match '/afficherCommande', :controller => 'users', :action => 'afficherCommande'
match '/Profil', :controller => 'users', :action => 'profilUser'
match '/show', :controller => 'users', :action => 'show'
match 'signup', :controller => 'users', :action => 'new'

resources :users

end

app/models/categori.rb
class Categori < ActiveRecord::Base
has_many :produits

validates :nom, :presence => true,
                :length => { :maximum => 50 }
validates :description, :presence => true,
                :length => { :maximum => 250 }
end

app/controllers/categoris_controller.rb
class CategorisController < ApplicationController
  # GET /categoris
  # GET /categoris.xml
  def index
    #params[:nom] c'est pour effectuer la recherche d'une categorie dans la liste
    @var=params[:nom] 
    if(params[:nom] == nil )
      @categoris = Categori.all
    else
      @categoris = Categori.find(:all, 
      :conditions=> ["nom like :eq", {:eq => @var + "%"}]) 
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categoris }
    end
  end

  # GET /categoris/1
  # GET /categoris/1.xml
  def show
    @categori = Categori.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @produit }
    end
  end

  # GET /categoris/new
  # GET /categoris/new.xml
  def new
    @categori = Categori.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @categori }
    end
  end

  # GET /categoris/1/edit
  def edit
    @categori = Categori.find(params[:id])
  end

  # POST /categoris
  # POST /categoris.xml
  def create
    @categori = Categori.new(params[:categori])

    respond_to do |format|
      if @categori.save
        format.html { redirect_to(@categori, :notice => 'La gategorie a ete cree avec succee.') }
        format.xml  { render :xml => @categori, :status => :created, :location => @categori }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @categori.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categoris/1
  # PUT /categoris/1.xml
  def update
    @categori = Categori.find(params[:id])

    respond_to do |format|
      if @categori.update_attributes(params[:categori])
        format.html { redirect_to(@categori, :notice => 'La gategorie a ete M.A.J avec succee.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @categori.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categoris/1
  # DELETE /categoris/1.xml
  def destroy
    @categori = Categori.find(params[:id])
    @categori.destroy
    respond_to do |format|
      format.html { redirect_to(categoris_url) }
      format.xml  { head :ok }
    end
  end

  def listProduit 
  # lister les produits par categoris
   # params[:nom] c'est pour rechercher un produit dans la liste des produits d'une categorie
    @pro = params[:nom]
    if( params[:nom] == nil )
      @categori = Categori.find(params[:categori])
      @produits = @categori.produits
    else
      @produits = Produit.find(:all, 
      :conditions=> ["nom like :eq ", {:eq =>  @pro + "%"}]) 
    end
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @produit }
    end
  end 
  
end

 

app/helpers/categoris_helper.rb
module CategorisHelper
end

app/views/categoris/_form.html.erb
<%= form_for(@categori) do |f| %>
  <% if @categori.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@categori.errors.count, "error") %> prohibited this categori from being saved:</h2>

      <ul>
      <% @categori.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br />
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoris/edit.html.erb
<h3>Modifier une categorie</h3>

<%= render 'form' %>

<%= link_to 'Visualiser', @categori %> |
<%= link_to 'Retour', categoris_path %>

app/views/categoris/index.html.erb
<h2>Categories des produits</h2>

<div id="recherche" class="round">
<% form_tag(:action => "index") do %><!-- Recherche de categorie -->
    <%= text_field_tag(:nom, params[:nom], :size => 5) %> 
    <%= submit_tag :"Recherche!" %>
<% end %>
</div>
<table id="listinfos">
<!--  <tr>
    <th>Nom</th>
    <th>Description</th>
  </tr>
-->

<% @categoris.each do |categori| %>

  <tr>
    <td class="nom"><%= link_to categori.nom, {:controller => "categoris", :action => "listProduit", :categori => categori}%></td>
    <td class="description"><%= link_to categori.description, {:controller => "categoris", :action => "listProduit", :categori => categori}%></td>
<!--    <td><%= link_to "Visualiser Produits", {:controller => "categoris", :action => "listProduit", :categori => categori}%></td>
-->    
    <% if current_user %>
      <% if current_user.admin == true %><!-- verifier si le user est un administrateur -->
        <td class="maintenance">
            <%= link_to 'Visualiser', categori %><br />
            <%= link_to 'Modifier', edit_categori_path(categori) %><br />
            <%= link_to 'Supprimer', {"id" => categori.id, :action => :destroy} %></td>
      <% end %>  
    <% end %>
  </tr>
<% end %>
</table>
<br/>
<% if current_user %>
    <% if current_user.admin == true %><!-- verifier si le user est un administrateur -->
        <%= link_to 'Nouvelle Categorie', new_categori_path %>
    <% end %>  
<% end %>

app/views/categoris/listCategori.html.erb
<h3>Séléctionner une categories</h3>

<table>
  <tr>
    <th>Categories</th>
  </tr>

<% @categoris.each do |categori| %>
  <tr>
    <td><%= categori.nom %></td>
   
     <td><%= link_to "Visualiser Produit", {:controller => "categoris", :action => "listProduit", :categori => categori}%></td>
  </tr>
<% end %>
</table>

<br/>

<% form_tag( :controller => "categoris" , :action => "index") do %>

		 <%= text_field_tag(:arg1, params[:arg1], :size => 5) %> &times
		
		<%= submit_tag :"recherche" %>
<% end %>

app/views/categoris/listProduit.html.erb
    <h2>
        <% if @categori %>
            Produits pour <%= @categori.nom %>&nbsp;: 
		<% else %>
            Recherche produits&nbsp;: 
		<% end %>
    </h2>
<div id="recherche" class="round">
<% form_tag(:action => "listProduit") do %> 
    <%= text_field_tag(:nom, params[:nom], :size => 5) %> 
    <%= submit_tag :"Recherche !" %>
<% end %>
</div>
<table id="listinfos">

<% @produits.each do |produit| %>
 
  <tr>
    <td class="nom"><%= link_to produit.nom, {:controller => "produits", :action => "afficher", :produit => produit}%></td>
    <td class="prix"><%= link_to produit.prix.to_s() + " €", {:controller => "produits", :action => "afficher", :produit => produit}%></td>
<!--    <td><%= link_to "Détail", {:controller => "produits", :action => "afficher", :produit => produit}%></td>
    <b><%= produit.nom %></b>
    Prix: 		<%= produit.prix %> euro

   <%= link_to "Détail", {:controller => "produits", :action => "afficher", :produit => produit} %>
  <br>
-->    
    <% if current_user %>
      <% if current_user.admin == true %>
        <td class="maintenance">
<!--            <%= link_to 'Visualiser', produit %><br />
-->
            <%= link_to 'Modifier', edit_produit_path(produit) %><br />
            <%= link_to 'Supprimer', {:controller => "produits", "id" => produit.id, :action => :destroy} %></td>

      <% end %>  
    <% end %>
  </tr>

<% end %>

</table>

<h3><%= link_to "Retour catégories", {:controller => "categoris", :action => "index"} %></h3>

  <% if current_user %>
      	<% if current_user.admin %><!-- verifier si le user est un administrateur -->
			<%= link_to 'Nouveau Produit', new_produit_path %>
		<% end %>
	<% end %>

app/views/categoris/new.html.erb
<h3>Ajouter une categorie</h3>

<%= render 'form' %>

<%= link_to 'Back', categoris_path %>

app/views/categoris/show.html.erb
<p id="notice"><%= notice %></p>
<h3>Categorie</h3>
<p>
  <b>Nom:</b>
  <%= @categori.nom %>
</p>
<p>
  <b>Description:</b>
  <%= @categori.description %>
</p>

<%= link_to 'Modifier', edit_categori_path(@categori) %> |
<%= link_to 'Retour', categoris_path %>