config/routes.rb
Ecommerce::Application.routes.draw do
root :controller => 'categoris', :action => 'index'

match '/', :controller => 'pages', :action => 'home'

match 'contact', :controller => 'pages', :action => 'contact'
match 'contact', :controller => 'pages', :action => 'contact'
match 'help', :controller => 'pages', :action => 'help'
match 'about', :controller => 'pages', :action => 'about'
resources :pages 

match 'commandes/:action', :controller => 'commandes', :action => /[a-z]+/i
match 'destroy', :controller => 'commandes', :action => 'destroy'
match 'payement', :controller => 'commandes', :action => 'payement'
match 'mesAchat', :controller => 'commandes', :action => 'mesAchat'
match 'commandeEffectuerUser', :controller => 'commandes', :action => 'commandeEffectuerUser'
resources :commandes 

match 'categoris/:action', :controller => 'categoris', :action => /[a-z]+/i
match 'listProduit', :controller => 'categoris', :action => 'listProduit'
match '/home', :controller => 'categoris', :action => 'index'
resources :categoris

match 'produits/:action', :controller => 'produits', :action => /[a-z]+/i
match 'produits/afficher', :controller => 'produits', :action => 'afficher'
match '/commandeEffectuer', :controller => 'produits', :action => 'commandeEffectuer'
resources :produits

match 'user_sessions/:action', :controller => 'user_sessions', :action => /[a-z]+/i
match 'login', :controller => 'user_sessions', :action => 'new'
match 'logout' => 'user_sessions#destroy', :as => :logout
resources :user_sessions

match '/afficherCommande', :controller => 'users', :action => 'afficherCommande'
match '/Profil', :controller => 'users', :action => 'profilUser'
match '/show', :controller => 'users', :action => 'show'
match 'signup', :controller => 'users', :action => 'new'

resources :users

end

app/models/commande.rb
class Commande < ActiveRecord::Base
	belongs_to :user
	belongs_to :produit

	def all_by_payer
		
			
	end
end

app/controllers/commandes_controller.rb
class CommandesController < ApplicationController
  # GET /commandes
  # GET /commandes.xml
  def index
    @titre = "Liste des commandes" 
    @commandes = Commande.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @commandes }
    end
  end

  # GET /commandes/1
  # GET /commandes/1.xml
  def show
    @titre = "visualiser une commande" 
    @commande = Commande.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @commande }
    end
  end

  # GET /commandes/new
  # GET /commandes/new.xml
  def new
    @titre = "Nouvelle commande" 
    #Ajout l'article au panier
    if current_user
      @commande = Commande.new(:produit_id => params[:format] ,:user_id => current_user.id,:payer => false)
      @commande.save
      @commandes = Commande.find_by_user_id(current_user.id)
    else
      redirect_to( :login, :notice => 'Veuillez vous Identifier') 

    end 
  end


  def destroy
    @titre = "Supprimer une commande" 
    @commande = Commande.find(params[:commande])
    @commande.destroy
          
       
  end
  # GET /commandes/1/edit
  def edit
    @commande = Commande.find(params[:id])
  end

  # POST /commandes
  # POST /commandes.xml
  def create
    @commande = Commande.new(params[:commande])
    
    respond_to do |format|
      if @commande.save
        format.html { redirect_to(@commande, :notice => 'Commande was successfully created.') }
        format.xml  { render :xml => @commande, :status => :created, :location => @commande }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @commande.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commandes/1
  # PUT /commandes/1.xml
  def update
    @titre = "M.A.J d'une commandes" 
    @commande = Commande.find(params[:id])

    respond_to do |format|
      if @commande.update_attributes(:payer => true)
        format.html { redirect_to(@commande, :notice => 'Votre commande a ete pris on compte.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @commande.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commandes/1
  # DELETE /commandes/1.xml
 

  def payement
    @commande = Commande.find(params[:commande])
  end

  def commandeEffectuer
    # lister juste les produits commander par les utilisateurs
    @commandes = Commande.find_all_by_payer(true) 
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @commandes }
    end
  end
  
  def mesAchat 
  # action qui affiche les commandes effectuer et le contenu du panier
    respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @commandes }
    end
  end  

  def commandeEffectuerUser
    # lister juste les produits commander par un utilisateur
    @commandes = Commande.find(:all, 
      :conditions=> ["payer = :eq and user_id = :id", {:eq =>  true, :id => current_user.id }]) 
    respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @commandes }
    end
  end

end

app/helpers/commandes_helper.rb
module CommandesHelper
end

app/views/commandes/_form.html.erb
<%= form_for(@commande) do |f| %>
  <% if @commande.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commande.errors.count, "error") %> prohibited this commande from being saved:</h2>

      <ul>
      <% @commande.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :produit_id %><br />
    <%= f.text_field :produit_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :payer %><br />
    <%= f.check_box :payer %>
  </div>
  <div class="actions">
    <%= f.submit 'valider'%>
  </div>
<% end %>

app/views/commandes/_payement.html.erb
<%= form_for(@commande) do |f| %>
  <% if @commande.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commande.errors.count, "error") %> prohibited this commande from being saved:</h2>

      <ul>
      <% @commande.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <label for="Titulaire">Titulaire_de_la_carte* : </label>
      <input type="text" name="Titulaire">
  </div>
  <div class="field">
      <label for="Numero">Numéro de la carte*    : </label>
      <input type="text" name="Numero">
  </div>
   <div class="field">
      <label for="mois">Date d'expiration (mm/aaaa)* : </label>
      <select id="mois" name="mois">
         <option value="valeur1">01</option>
         <option value="valeur2">02</option>
         <option value="valeur3">03</option>
         <option value="valeur4">04</option>
         <option value="valeur5">05</option>
         <option value="valeur6">06</option>
         <option value="valeur7">07</option>
         <option value="valeur8">08</option>
         <option value="valeur9">09</option>
         <option value="valeur10">10</option>
         <option value="valeur11">11</option>
         <option value="valeur12">12</option>
      </select> 
      <select id="annee" name="annee">
         <option value="valeur1">2013</option>
         <option value="valeur2">2014</option>
         <option value="valeur3">2015</option>
         <option value="valeur4">2016</option>
         <option value="valeur5">2017</option>
         <option value="valeur6">2018</option>
         <option value="valeur7">2019</option>
         <option value="valeur8">2020</option>
         <option value="valeur9">2021</option>
         <option value="valeur10">2022</option>
         <option value="valeur11">2023</option>
         <option value="valeur12">2024</option>
      </select>
  </div>
  <div class="field">
      <label for="code">Code de vérification de la carte* : </label>
      <input type="text" name="code">
  </div>
 
  <div class="actions">
    <%= f.submit 'valider'%>
  </div>
<% end %>

app/views/commandes/commandeEffectuer.html.erb
<h3>Liste des commandes</h3>

<table>
  <tr>
    <th align='center'>Produit</th>
    <th align='center'>Client</th>
    <th align='center'>Payement</th>
    <th align='center'></th>
  </tr>

<% @commandes.each do |commande| %>
  <tr>
    <td align='center'><%= Produit.find_by_id(commande.produit_id).nom %></td>
    <td align='center'><%= User.find_by_id(commande.user_id).username %></td>
    
      <td align='center'>
        <% if commande.payer%>
          <%= "Effectuer"%>
        <%  else %>
          <%= "en Attente"%>
        <% end %>
      </td>
      <td align='center'><%= link_to "Supprimer", {:controller => "commandes", :action => "destroy",:commande => commande}%></td>
  
  </tr>
<% end %>
</table>

<br />

app/views/commandes/commandeEffectuerUser.html.erb
<h3>Liste commandes</h3>

<table>
  <tr>
    <th align='center'>Produit</th>
    <th align='center'>Commander</th>
  </tr>

<% @commandes.each do |commande| %>
  <tr>
    <!-- afficher commande effectuer -->
    <td align='center'><%= Produit.find_by_id(commande.produit_id).nom %></td>
    
    <td align='center'><% if commande.payer %>
             <%=  "Effectuer" %>
            <% else %>
               <%=  "En attente" %>
        <% end %>
    </td>
    
  </tr>
<% end %>
</table>
<br/>
<%= link_to "Retour", {:controller => "commandes", :action => "mesAchat"}%>

app/views/commandes/destroy.html.erb
<h3>Produit retirer du panier</h3>

	
 	 <% if current_user %>
      	<% if current_user.admin %><!-- verifier si le user est un administrateur -->
      	<%= link_to "Retour", {:controller => "commandes", :action => "commandeEffectuer"}%>
      	<% else %>
      		<%= link_to "Voir votre panier", {:controller => "users", :action => "afficherCommande"}%>
			<%= link_to 'Retour', home_path %>
      	<% end %>
	<% end %>

app/views/commandes/edit.html.erb
<h3>Modifier commande</h3>

<%= render 'form' %>

<%= link_to 'Show', @commande %> |
<%= link_to 'Back', commandes_path %>

app/views/commandes/index.html.erb
<h1>Listing commandes</h1>

<table>
  <tr>
    <th align='center'>Produit</th>
    <th align='center'>User</th>
    <th align='center'>Payer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @commandes.each do |commande| %>
  <tr>
    <td align='center'><%= Produit.find_by_id(commande.produit_id).nom %></td>
    <td align='center'><%= User.find_by_id(commande.user_id).username %></td>
    <td align='center'><%= commande.payer %></td>
    <td align='center'><%= link_to 'Show', commande %></td>
    <td align='center'><%= link_to 'Edit', edit_commande_path(commande) %></td>
    <td align='center'><%= link_to 'Destroy', commande, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'creer Commande', new_commande_path %>

app/views/commandes/mesAchat.html.erb
<h2>Historique des achats </h2>
<br /><br /><br /><br />
<h3><%= link_to "Mon panier", {:controller => "users", :action => "afficherCommande"}%></h3>
<h3><%= link_to "Mes commandes", {:controller => "commandes", :action => "commandeEffectuerUser"}%></h3>

app/views/commandes/new.html.erb
<h1>Produit Ajouter au panier</h1>

<%= link_to "Mon panier", {:controller => "users", :action => "afficherCommande"}%>
<%= link_to 'Back', home_path %>

app/views/commandes/payement.html.erb
<h3>Payement en ligne</h3>

<%= render 'payement' %>

app/views/commandes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Produit:</b>
  <%= Produit.find_by_id(@commande.produit_id).nom %>
</p>

<%= link_to "Back", {:controller => "users", :action => "afficherCommande"}%>