config/routes.rb
Ecommerce::Application.routes.draw do
root :controller => 'categoris', :action => 'index'

match '/', :controller => 'pages', :action => 'home'

match 'contact', :controller => 'pages', :action => 'contact'
match 'contact', :controller => 'pages', :action => 'contact'
match 'help', :controller => 'pages', :action => 'help'
match 'about', :controller => 'pages', :action => 'about'
resources :pages 

match 'commandes/:action', :controller => 'commandes', :action => /[a-z]+/i
match 'destroy', :controller => 'commandes', :action => 'destroy'
match 'payement', :controller => 'commandes', :action => 'payement'
match 'mesAchat', :controller => 'commandes', :action => 'mesAchat'
match 'commandeEffectuerUser', :controller => 'commandes', :action => 'commandeEffectuerUser'
resources :commandes 

match 'categoris/:action', :controller => 'categoris', :action => /[a-z]+/i
match 'listProduit', :controller => 'categoris', :action => 'listProduit'
match '/home', :controller => 'categoris', :action => 'index'
resources :categoris

match 'produits/:action', :controller => 'produits', :action => /[a-z]+/i
match 'produits/afficher', :controller => 'produits', :action => 'afficher'
match '/commandeEffectuer', :controller => 'produits', :action => 'commandeEffectuer'
resources :produits

match 'user_sessions/:action', :controller => 'user_sessions', :action => /[a-z]+/i
match 'login', :controller => 'user_sessions', :action => 'new'
match 'logout' => 'user_sessions#destroy', :as => :logout
resources :user_sessions

match '/afficherCommande', :controller => 'users', :action => 'afficherCommande'
match '/Profil', :controller => 'users', :action => 'profilUser'
match '/show', :controller => 'users', :action => 'show'
match 'signup', :controller => 'users', :action => 'new'

resources :users

end

app/views/layouts/_footer.html.erb
<footer>        
	<nav class="round">
		 	<%= link_to "  A Propos  ", {:controller => "pages", :action => "about"}  %></li>
			<%= link_to "  Contact  ", {:controller => "pages", :action => "contact"}  %></li>
			<%= link_to "  Aide  ", {:controller => "pages", :action => "help"} %></li>
		
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	       
	<div id="logo">
    <%= image_tag("logo.jpeg", :alt => "Site Ecommerce ", :class => "round") %>	
    </div>
	<nav class="round">
        <div id="navclient" class="round">
		 	<% if current_user %>
		 	<!-- nom de l'utilisateur identifider -->
				<li>Bienvenu <%= current_user.username%></li>
				<!-- se deconnecter -->
				<li><%= link_to " Déconnexion ", :logout %></li>
				<!-- afficher le profil -->
				<li><%= link_to "Profile", {:controller => "users", :action => "profilUser"}%></li>
					<% if !current_user.admin %>
						<!-- afficher le panier et les commandes effectuer  -->
						<li><%= link_to "Mes achat", {:controller => "commandes", :action => "mesAchat"}%></li>
					<% end %>

			<% else %>
					<li><%= link_to " Inscription ", new_user_path%> </li>
					<li><%= link_to " Connexion ", :login %></li>
			<% end %>
			<li><%= link_to " Accueil ", home_path %></li>
        </div>
		 	<% if current_user %>
					<% if current_user.admin %>
                        <div id="navadmin" class="round">
						<li><%= link_to " Produit ", produits_path %></li>
						<li><%= link_to " Catégorie ", categoris_path %></li>
						<li><%= link_to " Utilisateurs ", users_path %></li>
						<li><%= link_to " Commandes ", {:controller => "commandes", :action => "commandeEffectuer"}%></li>
                        </div>
					<% end %>
            <% end %>
	</nav>

</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
 <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
 <!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		
		<title><%= @titre %></title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
	</head>
	<body>
		 <div class="container">
		      <%= render 'layouts/header' %>
              <div id="corps">
		      <section class="round">
		 		<%= yield %>
			 </section>
             </div>
			 <%= render 'layouts/footer' %>
		</div>
	</body>
</html>